version: '3.9'
services:
  postgres:
    image: postgres
    container_name: test_acl_db
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
    ports:
      - 5432:${PG_PORT}
